# Form implementation generated from reading ui file 'status_bar.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_status_bar(object):
    def setupUi(self, status_bar):
        status_bar.setObjectName("status_bar")
        status_bar.resize(890, 199)
        self.horizontalLayout = QtWidgets.QHBoxLayout(status_bar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sb_label_tem = QtWidgets.QLabel(parent=status_bar)
        self.sb_label_tem.setObjectName("sb_label_tem")
        self.horizontalLayout.addWidget(self.sb_label_tem)
        self.line_2 = QtWidgets.QFrame(parent=status_bar)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.sb_label_singla = QtWidgets.QLabel(parent=status_bar)
        self.sb_label_singla.setObjectName("sb_label_singla")
        self.horizontalLayout.addWidget(self.sb_label_singla)
        self.line = QtWidgets.QFrame(parent=status_bar)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.sb_progress_bar = QtWidgets.QProgressBar(parent=status_bar)
        self.sb_progress_bar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_progress_bar.sizePolicy().hasHeightForWidth())
        self.sb_progress_bar.setSizePolicy(sizePolicy)
        self.sb_progress_bar.setMinimumSize(QtCore.QSize(200, 0))
        self.sb_progress_bar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.sb_progress_bar.setProperty("value", 0)
        self.sb_progress_bar.setTextVisible(False)
        self.sb_progress_bar.setFormat("")
        self.sb_progress_bar.setObjectName("sb_progress_bar")
        self.horizontalLayout.addWidget(self.sb_progress_bar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)

        self.retranslateUi(status_bar)
        QtCore.QMetaObject.connectSlotsByName(status_bar)

    def retranslateUi(self, status_bar):
        _translate = QtCore.QCoreApplication.translate
        status_bar.setWindowTitle(_translate("status_bar", "Form"))
        self.sb_label_tem.setText(_translate("status_bar", "TEM Status: Uninitialized"))
        self.sb_label_singla.setText(_translate("status_bar", "SINGLA Status: Uninitialized"))
